<?php

use Illuminate\Database\Seeder;
use App\districts;

class DistrictTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        districts::create(['name' => 'TirinKOT', 'province_id' => 1]);
        districts::create(['name' => 'Chora', 'province_id' => 1]);
        districts::create(['name' => 'Khaz Oruzgan', 'province_id' => 1]);
        districts::create(['name' => 'Dahr Aword', 'province_id' => 1]);
        districts::create(['name' => 'Shahid Hasas', 'province_id' => 1]);
        districts::create(['name' => 'Gizab', 'province_id' => 1]);
        districts::create(['name' => 'Ab Kamari', 'province_id' => 2]);
        districts::create(['name' => 'Jawand', 'province_id' => 2]);
        districts::create(['name' => 'Ghormach', 'province_id' => 2]);
        districts::create(['name' => 'Qadis', 'province_id' => 2]);
        districts::create(['name' => 'Qala-I-Naw', 'province_id' => 2]);
        districts::create(['name' => 'Bala Morghab', 'province_id' => 2]);
        districts::create(['name' => 'Muqar', 'province_id' => 2]);
        districts::create(['name' => 'Bamyan', 'province_id' => 3]);
        districts::create(['name' => 'Kohmard', 'province_id' => 3]);
        districts::create(['name' => 'Panjab', 'province_id' => 3]);
        districts::create(['name' => 'Sayghan', 'province_id' => 3]);
        districts::create(['name' => 'Shibar', 'province_id' => 3]);
        districts::create(['name' => 'Waras', 'province_id' => 3]);
        districts::create(['name' => 'Yakawlang', 'province_id' => 3]);
        districts::create(['name' => 'Arghanj Khawa', 'province_id' => 4]);
        districts::create(['name' => 'Argo', 'province_id' => 4]);
        districts::create(['name' => 'Ishkashim', 'province_id' => 4]);
        districts::create(['name' => 'Baharak', 'province_id' => 4]);
        districts::create(['name' => 'Tagab', 'province_id' => 4]);
        districts::create(['name' => 'Tishkan', 'province_id' => 4]);
        districts::create(['name' => 'Jurm', 'province_id' => 4]);
        districts::create(['name' => 'Khash', 'province_id' => 4]);
        districts::create(['name' => 'Khawahan', 'province_id' => 4]);
        districts::create(['name' => 'Daraym', 'province_id' => 4]);
        districts::create(['name' => 'Maimay', 'province_id' => 4]);
        districts::create(['name' => 'Nusay', 'province_id' => 4]);
        districts::create(['name' => 'Raghistan', 'province_id' => 4]);
        districts::create(['name' => 'Zebak', 'province_id' => 4]);
        districts::create(['name' => 'Shighnan', 'province_id' => 4]);
        districts::create(['name' => 'Shekay', 'province_id' => 4]);
        districts::create(['name' => 'Shuhada', 'province_id' => 4]);
        districts::create(['name' => 'Shahri Buzurg', 'province_id' => 4]);
        districts::create(['name' => 'Fayzabad', 'province_id' => 4]);
        districts::create(['name' => 'Kuran Wa Munjan', 'province_id' => 4]);
        districts::create(['name' => 'Kishim', 'province_id' => 4]);
        districts::create(['name' => 'Kuf Ab', 'province_id' => 4]);
        districts::create(['name' => 'Kohistan', 'province_id' => 4]);
        districts::create(['name' => 'Wakhan', 'province_id' => 4]);
        districts::create(['name' => 'Wurduj', 'province_id' => 4]);
        districts::create(['name' => 'Yawan', 'province_id' => 4]);
        districts::create(['name' => 'Yaftali Paeen', 'province_id' => 4]);
        districts::create(['name' => 'Yamgan', 'province_id' => 4]);
        districts::create(['name' => 'Andarab', 'province_id' => 5]);
        districts::create(['name' => 'Baghlan Jadid', 'province_id' => 5]);
        districts::create(['name' => 'Burka', 'province_id' => 5]);
        districts::create(['name' => 'Puli Hisar', 'province_id' => 5]);
        districts::create(['name' => 'Puli KHumri', 'province_id' => 5]);
        districts::create(['name' => 'Tala Wa Barfak', 'province_id' => 5]);
        districts::create(['name' => 'Jalka', 'province_id' => 5]);
        districts::create(['name' => 'Hinjan', 'province_id' => 5]);
        districts::create(['name' => 'Khost Wa Fereng', 'province_id' => 5]);
        districts::create(['name' => 'Dushi', 'province_id' => 5]);
        districts::create(['name' => 'Dahana i Ghuri', 'province_id' => 5]);
        districts::create(['name' => 'Dih Salah', 'province_id' => 5]);
        districts::create(['name' => 'Farang Wa Gharu', 'province_id' => 5]);
        districts::create(['name' => 'Guzargahi Nor', 'province_id' => 5]);
        districts::create(['name' => 'Nahrin', 'province_id' => 5]);
        districts::create(['name' => 'Balkh', 'province_id' => 6]);
        districts::create(['name' => 'Char Pulak', 'province_id' => 6]);
        districts::create(['name' => 'Chahar kint', 'province_id' => 6]);
        districts::create(['name' => 'Chamtal', 'province_id' => 6]);
        districts::create(['name' => 'khulmi', 'province_id' => 6]);
        districts::create(['name' => 'Dawlatabad', 'province_id' => 6]);
        districts::create(['name' => 'Dihdadi', 'province_id' => 6]);
        districts::create(['name' => 'Zari', 'province_id' => 6]);
        districts::create(['name' => 'Shortepa', 'province_id' => 6]);
        districts::create(['name' => 'Sholgara', 'province_id' => 6]);
        districts::create(['name' => 'Kishindi', 'province_id' => 6]);
        districts::create(['name' => 'Kaldar', 'province_id' => 6]);
        districts::create(['name' => 'Marmul', 'province_id' => 6]);
        districts::create(['name' => 'Mazar-e Sharif', 'province_id' => 6]);
        districts::create(['name' => 'Guzargah-e Nor', 'province_id' => 6]);
        districts::create(['name' => 'Bagram', 'province_id' => 7]);
        districts::create(['name' => 'Jabal Saraj', 'province_id' => 7]);
        districts::create(['name' => 'Charika', 'province_id' => 7]);
        districts::create(['name' => 'Salang', 'province_id' => 7]);
        districts::create(['name' => 'Surkhi Parsa', 'province_id' => 7]);
        districts::create(['name' => 'Seyed Khil', 'province_id' => 7]);
        districts::create(['name' => 'Shekh Ali', 'province_id' => 7]);
        districts::create(['name' => 'Shinwari', 'province_id' => 7]);
        districts::create(['name' => 'Ghorband', 'province_id' => 7]);
        districts::create(['name' => 'Kohi Safi', 'province_id' => 7]);
        districts::create(['name' => 'Ahmadabad', 'province_id' => 8]);
        districts::create(['name' => 'Jaji', 'province_id' => 8]);
        districts::create(['name' => 'Jani Khil', 'province_id' => 8]);
        districts::create(['name' => 'Chawuk', 'province_id' => 8]);
        districts::create(['name' => 'Chamkani', 'province_id' => 8]);
        districts::create(['name' => 'Dand Wa Patan', 'province_id' => 8]);
        districts::create(['name' => 'Zargan/Zardan', 'province_id' => 8]);
        districts::create(['name' => 'Zurmat', 'province_id' => 8]);
        districts::create(['name' => 'Seyed Karam', 'province_id' => 8]);
        districts::create(['name' => 'Shawak', 'province_id' => 8]);
        districts::create(['name' => 'Ali Khil', 'province_id' => 8]);
        districts::create(['name' => 'Gardiz', 'province_id' => 8]);
        districts::create(['name' => 'Lazha Ahmad Khel', 'province_id' => 8]);
        districts::create(['name' => 'Urgun', 'province_id' => 9]);
        districts::create(['name' => 'Omna', 'province_id' => 9]);
        districts::create(['name' => 'Barmal', 'province_id' => 9]);
        districts::create(['name' => 'Terwa', 'province_id' => 9]);
        districts::create(['name' => 'Jani Khil', 'province_id' => 9]);
        districts::create(['name' => 'Dila Wa Khoshamand', 'province_id' => 9]);
        districts::create(['name' => 'Zarghun Shahr', 'province_id' => 9]);
        districts::create(['name' => 'Ziruk', 'province_id' => 9]);
        districts::create(['name' => 'Sar-e Hawza', 'province_id' => 9]);
        districts::create(['name' => 'Sarubi', 'province_id' => 9]);
        districts::create(['name' => 'Sharan', 'province_id' => 9]);
        districts::create(['name' => 'Gomal', 'province_id' => 9]);
        districts::create(['name' => 'Gayan', 'province_id' => 9]);
        districts::create(['name' => 'Matahan', 'province_id' => 9]);
        districts::create(['name' => 'Naka', 'province_id' => 9]);
        districts::create(['name' => 'Waza Khwa', 'province_id' => 9]);
        districts::create(['name' => 'Wor Mamay', 'province_id' => 9]);
        districts::create(['name' => 'Yahya Khil', 'province_id' => 9]);
        districts::create(['name' => 'Yosuf Khil', 'province_id' => 9]);
        districts::create(['name' => 'Anaba', 'province_id' => 10]);
        districts::create(['name' => 'Bazarak', 'province_id' => 10]);
        districts::create(['name' => 'Paryan', 'province_id' => 10]);
        districts::create(['name' => 'Khinji', 'province_id' => 10]);
        districts::create(['name' => 'Darah', 'province_id' => 10]);
        districts::create(['name' => 'Rokha', 'province_id' => 10]);
        districts::create(['name' => 'Shotul', 'province_id' => 10]);
        districts::create(['name' => 'Ishkamish', 'province_id' => 11]);
        districts::create(['name' => 'Bangi', 'province_id' => 11]);
        districts::create(['name' => 'Baharak', 'province_id' => 11]);
        districts::create(['name' => 'Taluqan', 'province_id' => 11]);
        districts::create(['name' => 'Chal', 'province_id' => 11]);
        districts::create(['name' => 'Chah Ab', 'province_id' => 11]);
        districts::create(['name' => 'Khwaja Baha Wudin', 'province_id' => 11]);
        districts::create(['name' => 'Khwaja Ghar', 'province_id' => 11]);
        districts::create(['name' => 'Darqad', 'province_id' => 11]);
        districts::create(['name' => 'Dashti Qala', 'province_id' => 11]);
        districts::create(['name' => 'Rustaq', 'province_id' => 11]);
        districts::create(['name' => 'Farkhar', 'province_id' => 11]);
        districts::create(['name' => 'Kalafgan', 'province_id' => 11]);
        districts::create(['name' => 'Namak Ab', 'province_id' => 11]);
        districts::create(['name' => 'Warsaj', 'province_id' => 11]);
        districts::create(['name' => 'Hazar Samuj', 'province_id' => 11]);
        districts::create(['name' => 'Yangi Qala', 'province_id' => 11]);
        districts::create(['name' => 'Aqcha', 'province_id' => 12]);
        districts::create(['name' => 'Khaniqa', 'province_id' => 12]);
        districts::create(['name' => 'Khamyab', 'province_id' => 12]);
        districts::create(['name' => 'Khwaja Do Koh', 'province_id' => 12]);
        districts::create(['name' => 'Darzab', 'province_id' => 12]);
        districts::create(['name' => 'Shibirghan', 'province_id' => 12]);
        districts::create(['name' => 'Fayzabad', 'province_id' => 12]);
        districts::create(['name' => 'Qarqin', 'province_id' => 12]);
        districts::create(['name' => 'Qush Tepa', 'province_id' => 12]);
        districts::create(['name' => 'Mardyan', 'province_id' => 12]);
        districts::create(['name' => 'Mingajik', 'province_id' => 12]);
        districts::create(['name' => 'Bak', 'province_id' => 13]);
        districts::create(['name' => 'Tany', 'province_id' => 13]);
        districts::create(['name' => 'Tery Zayi', 'province_id' => 13]);
        districts::create(['name' => 'Haji Maidan', 'province_id' => 13]);
        districts::create(['name' => 'Khust Matun', 'province_id' => 13]);
        districts::create(['name' => 'Spera', 'province_id' => 13]);
        districts::create(['name' => 'Shamal', 'province_id' => 13]);
        districts::create(['name' => 'Sabri', 'province_id' => 13]);
        districts::create(['name' => 'Qalandar', 'province_id' => 13]);
        districts::create(['name' => 'Guroz', 'province_id' => 13]);
        districts::create(['name' => 'Manduzi', 'province_id' => 13]);
        districts::create(['name' => 'Musa Khil', 'province_id' => 13]);
        districts::create(['name' => 'Nadir Shah Kot', 'province_id' => 13]);
        districts::create(['name' => 'Ishtarlay', 'province_id' => 14]);
        districts::create(['name' => 'Khadir', 'province_id' => 14]);
        districts::create(['name' => 'Sang', 'province_id' => 14]);
        districts::create(['name' => 'Takht', 'province_id' => 14]);
        districts::create(['name' => 'Sharistan', 'province_id' => 14]);
        districts::create(['name' => 'Kajran', 'province_id' => 14]);
        districts::create(['name' => 'Gizab', 'province_id' => 14]);
        districts::create(['name' => 'Miramor', 'province_id' => 14]);
        districts::create(['name' => 'Nili', 'province_id' => 14]);
        districts::create(['name' => 'Atghar', 'province_id' => 15]);
        districts::create(['name' => 'Arghandab', 'province_id' => 15]);
        districts::create(['name' => 'Tarang Wa Jaldak', 'province_id' => 15]);
        districts::create(['name' => 'Daychopan', 'province_id' => 15]);
        districts::create(['name' => 'Shah Joy', 'province_id' => 15]);
        districts::create(['name' => 'Shamulzayi', 'province_id' => 15]);
        districts::create(['name' => 'Shikay', 'province_id' => 15]);
        districts::create(['name' => 'Qalat', 'province_id' => 15]);
        districts::create(['name' => 'Kakar', 'province_id' => 15]);
        districts::create(['name' => 'Mizan', 'province_id' => 15]);
        districts::create(['name' => 'Balkhab', 'province_id' => 16]);
        districts::create(['name' => 'Sar-e Pol', 'province_id' => 16]);
        districts::create(['name' => 'Sangcharak', 'province_id' => 16]);
        districts::create(['name' => 'Suzma Qala', 'province_id' => 16]);
        districts::create(['name' => 'Sayyad', 'province_id' => 16]);
        districts::create(['name' => 'Kohistanat', 'province_id' => 16]);
        districts::create(['name' => 'Gusfandi', 'province_id' => 16]);
        districts::create(['name' => 'Aybak', 'province_id' => 17]);
        districts::create(['name' => 'Hazrat-i Sultan', 'province_id' => 17]);
        districts::create(['name' => 'Khuram Wa Sarbagh', 'province_id' => 17]);
        districts::create(['name' => 'Dara-I-Sufi Bala', 'province_id' => 17]);
        districts::create(['name' => 'Dara-I-Sufi Payan', 'province_id' => 17]);
        districts::create(['name' => 'Roye Do Ab', 'province_id' => 17]);
        districts::create(['name' => 'Firuz Nakhchir', 'province_id' => 17]);
        districts::create(['name' => 'Ab Band', 'province_id' => 18]);
        districts::create(['name' => 'Ajristan', 'province_id' => 18]);
        districts::create(['name' => 'Andar', 'province_id' => 18]);
        districts::create(['name' => 'Bahram Shahid', 'province_id' => 18]);
        districts::create(['name' => 'Jaghuri', 'province_id' => 18]);
        districts::create(['name' => 'Khwaja Umari', 'province_id' => 18]);
        districts::create(['name' => 'Dih Yak', 'province_id' => 18]);
        districts::create(['name' => 'Rashidan', 'province_id' => 18]);
        districts::create(['name' => 'Zana Khan', 'province_id' => 18]);
        districts::create(['name' => 'Ghazni', 'province_id' => 18]);
        districts::create(['name' => 'Qarabagh', 'province_id' => 18]);
        districts::create(['name' => 'Giro', 'province_id' => 18]);
        districts::create(['name' => 'Gilan', 'province_id' => 18]);
        districts::create(['name' => 'Malistan', 'province_id' => 18]);
        districts::create(['name' => 'Muqar', 'province_id' => 18]);
        districts::create(['name' => 'Nawur', 'province_id' => 18]);
        districts::create(['name' => 'Nawa', 'province_id' => 18]);
        districts::create(['name' => 'Waghaz', 'province_id' => 18]);
        districts::create(['name' => 'Wali Mohamd Shahid Khogyani', 'province_id' => 18]);
        districts::create(['name' => 'Yasaband', 'province_id' => 19]);
        districts::create(['name' => 'Tulak', 'province_id' => 19]);
        districts::create(['name' => 'Taywara', 'province_id' => 19]);
        districts::create(['name' => 'Dawlat Yar', 'province_id' => 19]);
        districts::create(['name' => 'Du Layna', 'province_id' => 19]);
        districts::create(['name' => 'Charsada', 'province_id' => 19]);
        districts::create(['name' => 'Firuz Koh', 'province_id' => 19]);
        districts::create(['name' => 'Saghar', 'province_id' => 19]);
        districts::create(['name' => 'Shahrak', 'province_id' => 19]);
        districts::create(['name' => 'Lal Wa Sarjangal', 'province_id' => 19]);
        districts::create(['name' => 'Almar', 'province_id' => 20]);
        districts::create(['name' => 'Andkhoy', 'province_id' => 20]);
        districts::create(['name' => 'Bilcheragh', 'province_id' => 20]);
        districts::create(['name' => 'Pashtun Kot', 'province_id' => 20]);
        districts::create(['name' => 'Khani Chahar Bagh', 'province_id' => 20]);
        districts::create(['name' => 'Dowlat Abad', 'province_id' => 20]);
        districts::create(['name' => 'Khwaja Sabz Posht', 'province_id' => 20]);
        districts::create(['name' => 'Shirin Tagab', 'province_id' => 20]);
        districts::create(['name' => 'Qarghan', 'province_id' => 20]);
        districts::create(['name' => 'Qaramqol', 'province_id' => 20]);
        districts::create(['name' => 'Qaysar', 'province_id' => 20]);
        districts::create(['name' => 'Kohistan', 'province_id' => 20]);
        districts::create(['name' => 'Gurziwan', 'province_id' => 20]);
        districts::create(['name' => 'Maymana', 'province_id' => 20]);
        districts::create(['name' => 'Anar Dara', 'province_id' => 21]);
        districts::create(['name' => 'Bala Buluk', 'province_id' => 21]);
        districts::create(['name' => 'Bakwa', 'province_id' => 21]);
        districts::create(['name' => 'Pur Chaman', 'province_id' => 21]);
        districts::create(['name' => 'Pusht Rod', 'province_id' => 21]);
        districts::create(['name' => 'Khak Safid', 'province_id' => 21]);
        districts::create(['name' => 'Shib Koh', 'province_id' => 21]);
        districts::create(['name' => 'Farah', 'province_id' => 21]);
        districts::create(['name' => 'Qala i Kah', 'province_id' => 21]);
        districts::create(['name' => 'Gulistan', 'province_id' => 21]);
        districts::create(['name' => 'Lash Wa Jawain', 'province_id' => 21]);
        districts::create(['name' => 'Arghistan', 'province_id' => 22]);
        districts::create(['name' => 'Arghandab', 'province_id' => 22]);
        districts::create(['name' => 'Panjwaye', 'province_id' => 22]);
        districts::create(['name' => 'Khakriz', 'province_id' => 22]);
        districts::create(['name' => 'Daman', 'province_id' => 22]);
        districts::create(['name' => 'Rigistan', 'province_id' => 22]);
        districts::create(['name' => 'Zhari', 'province_id' => 22]);
        districts::create(['name' => 'Spin Boldak', 'province_id' => 22]);
        districts::create(['name' => 'Shah Wali Kot', 'province_id' => 22]);
        districts::create(['name' => 'Shorabak', 'province_id' => 22]);
        districts::create(['name' => 'Ghorak', 'province_id' => 22]);
        districts::create(['name' => 'Ghandahar', 'province_id' => 22]);
        districts::create(['name' => 'Miyan Nasheen', 'province_id' => 22]);
        districts::create(['name' => 'Maiwand', 'province_id' => 22]);
        districts::create(['name' => 'Nish', 'province_id' => 22]);
        districts::create(['name' => 'Istalif', 'province_id' => 23]);
        districts::create(['name' => 'Bagrami', 'province_id' => 23]);
        districts::create(['name' => 'Paghman', 'province_id' => 23]);
        districts::create(['name' => 'Chahar Asyab', 'province_id' => 23]);
        districts::create(['name' => 'Khak Jabar', 'province_id' => 23]);
        districts::create(['name' => 'Deh Sabz', 'province_id' => 23]);
        districts::create(['name' => 'Sorubi', 'province_id' => 23]);
        districts::create(['name' => 'Shakar Dara', 'province_id' => 23]);
        districts::create(['name' => 'Farza', 'province_id' => 23]);
        districts::create(['name' => 'Kabul', 'province_id' => 23]);
        districts::create(['name' => 'Kalkan', 'province_id' => 23]);
        districts::create(['name' => 'Guldara', 'province_id' => 23]);
        districts::create(['name' => 'Mussani', 'province_id' => 23]);
        districts::create(['name' => 'Mir Bacha Kot', 'province_id' => 23]);
        districts::create(['name' => 'Gharabaq', 'province_id' => 23]);
        districts::create(['name' => 'Alasay', 'province_id' => 24]);
        districts::create(['name' => 'Tagab', 'province_id' => 24]);
        districts::create(['name' => 'Hesa Awal Kohistan', 'province_id' => 24]);
        districts::create(['name' => 'Hesa Duwum Kohistan', 'province_id' => 24]);
        districts::create(['name' => 'Koh Band', 'province_id' => 24]);
        districts::create(['name' => 'Mahmod Raghi', 'province_id' => 24]);
        districts::create(['name' => 'Najrab', 'province_id' => 24]);
        districts::create(['name' => 'Imam Sahib', 'province_id' => 25]);
        districts::create(['name' => 'Chahar Dara', 'province_id' => 25]);
        districts::create(['name' => 'Khanabad', 'province_id' => 25]);
        districts::create(['name' => 'Dasht Archi', 'province_id' => 25]);
        districts::create(['name' => 'Ali Abad', 'province_id' => 25]);
        districts::create(['name' => 'Qala-I-Zal', 'province_id' => 25]);
        districts::create(['name' => 'Konduz', 'province_id' => 25]);
        districts::create(['name' => 'Asadabad', 'province_id' => 26]);
        districts::create(['name' => 'Bar Kunar', 'province_id' => 26]);
        districts::create(['name' => 'Khas Kunar', 'province_id' => 26]);
        districts::create(['name' => 'Dangam', 'province_id' => 26]);
        districts::create(['name' => 'Dar-I-Pech', 'province_id' => 26]);
        districts::create(['name' => 'Chapa Dara', 'province_id' => 26]);
        districts::create(['name' => 'Chawky', 'province_id' => 26]);
        districts::create(['name' => 'Sirkanay', 'province_id' => 26]);
        districts::create(['name' => 'Shaygal Wa Shiltan', 'province_id' => 26]);
        districts::create(['name' => 'Ghazi Abad', 'province_id' => 26]);
        districts::create(['name' => 'Marwara', 'province_id' => 26]);
        districts::create(['name' => 'Nari', 'province_id' => 26]);
        districts::create(['name' => 'Narang', 'province_id' => 26]);
        districts::create(['name' => 'Norgul', 'province_id' => 26]);
        districts::create(['name' => 'Wata Por', 'province_id' => 26]);
        districts::create(['name' => 'Dawlat Shah', 'province_id' => 27]);
        districts::create(['name' => 'Qarghayi', 'province_id' => 27]);
        districts::create(['name' => 'Ayshang', 'province_id' => 27]);
        districts::create(['name' => 'Alingar', 'province_id' => 27]);
        districts::create(['name' => 'Mehtar Lam', 'province_id' => 27]);
        districts::create(['name' => 'Arzarah', 'province_id' => 28]);
        districts::create(['name' => 'Baraky', 'province_id' => 28]);
        districts::create(['name' => 'Pol-I-Alam', 'province_id' => 28]);
        districts::create(['name' => 'Charkh', 'province_id' => 28]);
        districts::create(['name' => 'Kharwar', 'province_id' => 28]);
        districts::create(['name' => 'Khoshi', 'province_id' => 28]);
        districts::create(['name' => 'Mohammad Agha', 'province_id' => 28]);
        districts::create(['name' => 'Barak', 'province_id' => 28]);
        districts::create(['name' => 'Achin', 'province_id' => 29]);
        districts::create(['name' => 'Bati Kot', 'province_id' => 29]);
        districts::create(['name' => 'Behsod', 'province_id' => 29]);
        districts::create(['name' => 'Pachir Wa Agam', 'province_id' => 29]);
        districts::create(['name' => 'Jalal Abad', 'province_id' => 29]);
        districts::create(['name' => 'Hesarak', 'province_id' => 29]);
        districts::create(['name' => 'Chaparhar', 'province_id' => 29]);
        districts::create(['name' => 'Khogyani', 'province_id' => 29]);
        districts::create(['name' => 'Dur Baba', 'province_id' => 29]);
        districts::create(['name' => 'Dar-I-Nor', 'province_id' => 29]);
        districts::create(['name' => 'Dih Bala', 'province_id' => 29]);
        districts::create(['name' => 'Rodat', 'province_id' => 29]);
        districts::create(['name' => 'Sorkh Rod', 'province_id' => 29]);
        districts::create(['name' => 'Shirzad', 'province_id' => 29]);
        districts::create(['name' => 'Shinwar', 'province_id' => 29]);
        districts::create(['name' => 'Kot', 'province_id' => 29]);
        districts::create(['name' => 'Kuz Kunar', 'province_id' => 29]);
        districts::create(['name' => 'Gushta', 'province_id' => 29]);
        districts::create(['name' => 'Lal Por', 'province_id' => 29]);
        districts::create(['name' => 'Muhmand Dara', 'province_id' => 29]);
        districts::create(['name' => 'Nazyan', 'province_id' => 29]);
        districts::create(['name' => 'Barg Matal', 'province_id' => 30]);
        districts::create(['name' => 'Parun', 'province_id' => 30]);
        districts::create(['name' => 'Dawab', 'province_id' => 30]);
        districts::create(['name' => 'Kamdish', 'province_id' => 30]);
        districts::create(['name' => 'Mandol', 'province_id' => 30]);
        districts::create(['name' => 'Nurgram', 'province_id' => 30]);
        districts::create(['name' => 'Wama', 'province_id' => 30]);
        districts::create(['name' => 'Waygal', 'province_id' => 30]);
        districts::create(['name' => 'Chakhansor', 'province_id' => 31]);
        districts::create(['name' => 'Char Burjak', 'province_id' => 31]);
        districts::create(['name' => 'Khash Rod', 'province_id' => 31]);
        districts::create(['name' => 'Zaranj', 'province_id' => 31]);
        districts::create(['name' => 'Kang', 'province_id' => 31]);
        districts::create(['name' => 'Jalriz', 'province_id' => 32]);
        districts::create(['name' => 'Jaghato', 'province_id' => 32]);
        districts::create(['name' => 'Chak-i-Wardak', 'province_id' => 32]);
        districts::create(['name' => 'Hisa-i-Awal Behsud', 'province_id' => 32]);
        districts::create(['name' => 'Daymir', 'province_id' => 32]);
        districts::create(['name' => 'Saydabad', 'province_id' => 32]);
        districts::create(['name' => 'Markaz', 'province_id' => 32]);
        districts::create(['name' => 'Behsud', 'province_id' => 32]);
        districts::create(['name' => 'Nirkh', 'province_id' => 32]);
        districts::create(['name' => 'Adraskan', 'province_id' => 33]);
        districts::create(['name' => 'Injil', 'province_id' => 33]);
        districts::create(['name' => 'Uba', 'province_id' => 33]);
        districts::create(['name' => 'Pashtun Zarghon', 'province_id' => 33]);
        districts::create(['name' => 'Chishti Sharif', 'province_id' => 33]);
        districts::create(['name' => 'Zinda Jan', 'province_id' => 33]);
        districts::create(['name' => 'Shindand', 'province_id' => 33]);
        districts::create(['name' => 'Ghurian', 'province_id' => 33]);
        districts::create(['name' => 'Farsi', 'province_id' => 33]);
        districts::create(['name' => 'Karukh', 'province_id' => 33]);
        districts::create(['name' => 'Kushk', 'province_id' => 33]);
        districts::create(['name' => 'Khushki Kuhna', 'province_id' => 33]);
        districts::create(['name' => 'Kuhsan', 'province_id' => 33]);
        districts::create(['name' => 'Guzara', 'province_id' => 33]);
        districts::create(['name' => 'Gulran', 'province_id' => 33]);
        districts::create(['name' => 'Baghran', 'province_id' => 34]);
        districts::create(['name' => 'Dishu', 'province_id' => 34]);
        districts::create(['name' => 'Rig Khan Nishin', 'province_id' => 34]);
        districts::create(['name' => 'Sangin', 'province_id' => 34]);
        districts::create(['name' => 'Kajaki', 'province_id' => 34]);
        districts::create(['name' => 'Garmsir', 'province_id' => 34]);
        districts::create(['name' => 'Lashkargah', 'province_id' => 34]);
        districts::create(['name' => 'Mussa Qala', 'province_id' => 34]);
        districts::create(['name' => 'Nad Ali', 'province_id' => 34]);
        districts::create(['name' => 'Nawa-i-Barikzayi', 'province_id' => 34]);
        districts::create(['name' => 'Nawzad', 'province_id' => 34]);
        districts::create(['name' => 'Nahr-i-Saraj', 'province_id' => 34]);
        districts::create(['name' => 'Washir', 'province_id' => 34]);
    }
}
